trigger:
  branches:
    include:
    - '*'
variables:
- name: buildConfiguration
  value: 'Release'
- name: wwwrootDir
  value: 'Tailspin.SpaceGame.Web/wwwroot'
- name: dotnetSdkVersion
  value: '9.x'
- name: nodeVersion  
  value: '18.x'     

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
      demands:
      - npm
    steps:
    # 👇 Install compatible Node.js version first
    - task: NodeTool@0
      displayName: 'Install Node.js $(nodeVersion)'
      inputs:
        versionSpec: '$(nodeVersion)'
    
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
        
    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false
        
    # ... rest of your steps remain unchanged ...
